FROM rust:latest

# Install required dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libasound2-dev \
        libjack-jackd2-dev \
        libjack-jackd2-0 \
        pkg-config \
        libdbus-1-dev \

# Set /cpal/ to working directory
WORKDIR /cpal
COPY . .

# When running this Docker container, ensure ALSA devices are exposed 
# using `--device /dev/snd` and `--group-add audio`