FROM rust:latest

# Install required dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libasound2-dev \
        libjack-jackd2-dev \
        libjack-jackd2-0 \
        pkg-config \

# Set /cpal/ to working directory
WORKDIR /cpal
COPY . .