version: 2

jobs:
  asmjs-test:
    working_directory: ~/cpal
    docker:
      - image: tomaka/rustc-emscripten
    steps:
      - run: apt-get -qq update && apt-get install -y git
      - checkout
      - restore_cache:
          key: asmjs-test-cache-{{ checksum "Cargo.toml" }}
      - run: cargo build --example beep --target asmjs-unknown-emscripten
      - save_cache:
          key: asmjs-test-cache-{{ checksum "Cargo.toml" }}
          paths:
            - target

  wasm-test:
    working_directory: ~/cpal
    docker:
      - image: tomaka/rustc-emscripten
    steps:
      - run: apt-get -qq update && apt-get install -y git
      - checkout
      - restore_cache:
          key: wasm-test-cache-{{ checksum "Cargo.toml" }}
      - run: cargo build --example beep --target wasm32-unknown-emscripten
      - save_cache:
          key: wasm-test-cache-{{ checksum "Cargo.toml" }}
          paths:
            - target
  
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - asmjs-test
      - wasm-test
