name: Determine MSRV for all-features
description: Computes the maximum MSRV needed for --all-features tests (platform vs JACK)

inputs:
  platform-msrv:
    description: The MSRV for the platform backend (e.g., ALSA, CoreAudio, Windows)
    required: true
  jack-msrv:
    description: The MSRV for JACK backend
    required: true
  pulseaudio-msrv:
    description: The MSRV for PulseAudio backend (optional, Linux only)
    required: false
    default: ''

outputs:
  all-features:
    description: The maximum MSRV to use for --all-features tests
    value: ${{ steps.compare.outputs.all-features }}

runs:
  using: composite
  steps:
    - name: Compare versions
      id: compare
      shell: bash
      run: |
        PLATFORM_MSRV="${{ inputs.platform-msrv }}"
        JACK_MSRV="${{ inputs.jack-msrv }}"
        PULSEAUDIO_MSRV="${{ inputs.pulseaudio-msrv }}"
        # Use sort -V to find the maximum version
        VERSIONS="$PLATFORM_MSRV $JACK_MSRV"
        if [ -n "$PULSEAUDIO_MSRV" ]; then
          VERSIONS="$VERSIONS $PULSEAUDIO_MSRV"
        fi
        MAX_MSRV=$(printf '%s\n' $VERSIONS | sort -V | tail -n1)
        echo "all-features=$MAX_MSRV" >> $GITHUB_OUTPUT
        echo "Platform MSRV: $PLATFORM_MSRV, JACK MSRV: $JACK_MSRV, PulseAudio MSRV: $PULSEAUDIO_MSRV, Using for --all-features: $MAX_MSRV"
